{
 "title": "Tibber",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "home", "label": "Home", "query": { "query": "tibber_home_info" } }
  ]
 },
 "panels": [
  {
   "title": "Current power consumption",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_consumption{home_id=\"$home\"})"
    }
   ]
  },
  {
   "title": "L1",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 1, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_current{home_id=\"$home\",line=\"1\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "L2",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 1, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_current{home_id=\"$home\",line=\"2\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "L3",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 1, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_current{home_id=\"$home\",line=\"3\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Current power price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kr/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_price{home_id=\"$home\", type=\"total\"})"
    }
   ]
  },
  {
   "title": "Power consumption pr. hour",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(increase(tibber_power_consumption_day_total{home_id=\"$home\"}[1h])) * 1000"
    }
   ]
  },
  {
   "title": "Relative price level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(tibber_power_price_level{home_id=\"$home\"}))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "sum(irate(tibber_power_consumption_day_total{home_id=\"$home\"}[$__rate_interval])) * 60 * 60",
     "legendFormat": "Power consumption"
    }
   ]
  },
  {
   "title": "Power consumption today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_consumption_day_total{home_id=\"$home\"})"
    }
   ]
  },
  {
   "title": "Cost pr. hour",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "sum(increase(tibber_power_cost_day_total{home_id=\"$home\"}[1h]))"
    }
   ]
  },
  {
   "title": "Avg today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_consumption_day_avg{home_id=\"$home\"})"
    }
   ]
  },
  {
   "title": "Max today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_consumption_day_max{home_id=\"$home\"})"
    }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "avg(tibber_power_price{home_id=\"$home\",type=\"total\"})",
     "legendFormat": "Price inc. tax"
    },
    {
     "expr": "avg(tibber_power_price{home_id=\"$home\",type=\"energy\"})",
     "legendFormat": "Price per kWh"
    }
   ]
  },
  {
   "title": "Cost today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_cost_day_total{home_id=\"$home\"})"
    }
   ]
  },
  {
   "title": "Price",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "avg(tibber_power_price{home_id=\"$home\",type=\"total\"})"
    }
   ]
  },
  {
   "title": "Cost selected period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tibber_power_cost_day_total{home_id=\"$home\"}[$__range]))"
    }
   ]
  }
 ]
}