{
 "title": "Tibber monthly",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "home", "label": "Home", "query": { "query": "tibber_home_info" } }
  ]
 },
 "panels": [
  {
   "title": "Consumption",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "label_replace(\n  quantile_over_time(0.9,tibber_power_consumption_previous_day{home_id=\"$home\"}[1d] offset -1d) + ignoring(year, month) group_right\n    count_values without() (\"year\", year(timestamp(\n      count_values without() (\"month\", month(timestamp(\n        quantile_over_time(0.9,tibber_power_consumption_previous_day{home_id=\"$home\"}[1d] offset -1d)\n      )))\n    ))) * 0,\n  \"zero\",\n  \"0\",\n  \"month\",\n  \"^[0-9]$\"\n)",
     "legendFormat": "{{year}}-{{zero}}{{month}}"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "label_replace(\n  quantile_over_time(0.9,tibber_power_cost_previous_day{home_id=\"$home\"}[1d] offset -1d) + ignoring(year, month) group_right\n    count_values without() (\"year\", year(timestamp(\n      count_values without() (\"month\", month(timestamp(\n        quantile_over_time(0.9,tibber_power_cost_previous_day{home_id=\"$home\"}[1d] offset -1d)\n      )))\n    ))) * 0,\n  \"zero\",\n  \"0\",\n  \"month\",\n  \"^[0-9]$\"\n)",
     "legendFormat": "{{year}}-{{zero}}{{month}}"
    }
   ]
  },
  {
   "title": "Average price",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "label_replace(\n  avg_over_time(tibber_power_price{home_id=\"$home\",type=\"total\"}[1d]) + ignoring(year, month) group_right\n    count_values without() (\"year\", year(timestamp(\n      count_values without() (\"month\", month(timestamp(\n        avg_over_time(tibber_power_price{home_id=\"$home\",type=\"total\"}[1d])\n      )))\n    ))) * 0,\n  \"zero\",\n  \"0\",\n  \"month\",\n  \"^[0-9]$\"\n)",
     "legendFormat": "{{year}}-{{zero}}{{month}}"
    }
   ]
  }
 ]
}