{
 "title": "Tibber (without pulse)",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "home", "label": "Home", "query": { "query": "tibber_home_info" } }
  ]
 },
 "panels": [
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "avg(tibber_power_price{home_id=\"$home\",type=\"total\"})",
     "legendFormat": "Price inc. tax"
    },
    {
     "expr": "avg(tibber_power_price{home_id=\"$home\",type=\"energy\"})",
     "legendFormat": "Price per kWh"
    }
   ]
  },
  {
   "title": "Current power price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kr/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_price{home_id=\"$home\", type=\"total\"})"
    }
   ]
  },
  {
   "title": "Price",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "avg(tibber_power_price{home_id=\"$home\",type=\"total\"})"
    }
   ]
  },
  {
   "title": "Relative price level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(tibber_power_price_level{home_id=\"$home\"}))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.9,tibber_power_consumption_previous_day{home_id=\"$home\"}[1d] offset -2d)) * 1000",
     "legendFormat": "Power consumption"
    }
   ]
  },
  {
   "title": "Consumption yesterday",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_consumption_previous_day{home_id=\"$home\"})"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.9,tibber_power_consumption_previous_day{home_id=\"$home\"}[1d] offset -1d)) * 1000",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.9,tibber_power_cost_previous_day{home_id=\"$home\"}[1d] offset -2d))",
     "legendFormat": "Power cost"
    }
   ]
  },
  {
   "title": "Cost yesterday",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tibber_power_cost_previous_day{home_id=\"$home\"})"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.9,tibber_power_cost_previous_day{home_id=\"$home\"}[1d] offset -1d))",
     "legendFormat": "Consumption"
    }
   ]
  }
 ]
}